#!/bin/bash -x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
user=$1
gport=$2
rcon=$3
rpass=$4
players=$5
seed=$6
hostname=$7
map_name=$8
dir=/home/$user/gamefiles/rust
sudo chown -R $user $dir

sudo su -s /bin/bash -c "killall -9 RustDedicated" $user

if [ -f /home/$user/gamefiles/.online ]
then
sudo rm /home/$user/gamefiles/.online
fi
#sudo rm /home/$user/gamefiles/.killed

sudo su -s /bin/bash -c "$DIR/startrust.sh $dir $user $gport $rcon $rpass $players $seed '$hostname' '$map_name' > ~/gamefiles/.runopt 2>&1 > /dev/null &" $user

