#!/bin/bash -x
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
user=$1
gport=$2
rcon=$3
rpass=$4
players=$5
seed=$6
dir=/home/$user/gamefiles/rust

sudo su -s /bin/bash -c $($DIR"/startrust.sh" $dir $user $gport $rcon $rpass $players $seed ) $user

