#!/bin/bash -x
user=$1

##check for directories
if [ -d "/home/gameuser/RustDedicated_Data/" ]
then

echo "ok continue"


sudo rsync -av "/home/gameuser/RustDedicated_Data/" "/home/"$user"/gamefiles/rust/RustDedicated_Data/"

sudo chown -R $user "/home/"$user"/gamefiles/rust"

else

echo "umod does not exits in gameuser directory" 

fi


#permission to execute